schema_registry/protobuf: Manually Render the proto
Signed-off-by: Ben Pope <ben@redpanda.com>
(cherry picked from commit 0ee8c738861b0d1701ad89050a42f69c40eb3699)

Conflicts:
  src/v/pandaproxy/schema_registry/protobuf.cc

Added a constructor to avoid
```
error: no viable constructor or deduction guide for deduction of template arguments of 'field_option'
```